### PR TITLE
🐛 Missing `FORMAT` parameter in server requests (WMS GetMap image format)

### LINKED ISSUE #763: GetMap WMS format is not used
### Checklist

- [x] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

The `wms_getmap_format` of /api/config API REST is not used by the Client.

If is set i.e. `JPG` format:

Image

The request to G3W-ADMIN for a WMS GetMap request is made without the image format parameter so the response is a PNG image. 

### Steps to reproduce

Try to change the `WMS GetMap image format` from insert/update project form and check the format is not used by the client.

### Environment

- g3w-admin: __v3.9.3__
- g3w-client: __3.11.6-HEAD__
    - qtimeseries: __3.9.0__
- browser: __Firefox 137.0__
- operating system: __Linux 64-bit__

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #763 

Set WMS GetMap image format within g3w-admin:

Screenshot_20250327_161048

## Before

FORMAT is missing

Screenshot_20250327_161334

## After

FORMAT parameter is set

Screenshot_20250327_161439

### CODE REVIEW

File: src/services/map.js [hunk 1]
```diff
@@ -1421,8 +1421,8 @@ class MapService extends G3WObject {
         {
           id: `layer_${id}`,
           projection: this.getProjection(),
-          /** @since 3.9.1 */
-          format: 1 === layers.length ? layer.getFormat() : null
+          /** @since 3.11.7 Get Format from layer */ 
+          format: layer.getFormat()
         },
         1 === layers.length ? {} : this.layersExtraParams
```
Comment (Raruto) [inline src/services/map.js]: @volterra79 double check, similar condition underneath:  `1 === layers.length ? {} : this.layersExtraParams`

Anyway, is `this.layersExtraParams` deprecated?

Comment (volterra79) [reply src/services/map.js]: @Raruto fix here https://github.com/g3w-suite/g3w-client/pull/764/commits/6f459b3f398d1d399d3058d0f1bf8fe8f47b405b

**Review by Raruto — APPROVED** [review]
