### PR TITLE
Prevent sending `BBOX=` parameter on `GetLegendGraphic` request when project has `context_base_legend: false` and the Legend is set to separate TAB

### LINKED ISSUE #342: Legend on Separate TAB has BBOX parameter when context_base_legend is false
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

If QGIS project has unchecked **Filter Legend by Map Content** (`context_base_legend: false` on project configuration )

Screenshot from 2023-02-14 10-58-10

REQUEST: GetLegendGraphic has BBOX parameter

### Steps to reproduce

1. Set QGIS project with  Filter Legend by Map Content unchecked
2. Set Legend position on separate TAB
Screenshot from 2023-02-14 11-07-08
3. Open a Legend Tab and check GetLegendGraphic request 

### Environment

- g3w-admin: v3.5
- g3w-client: v3.7.x
- browser: all

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #342

### CODE REVIEW

File: src/components/CatalogLayersLegendItems.vue [hunk 1]
```diff
@@ -126,28 +186,45 @@ export default {
...
 
       }
-
       for (const method in urlMethodsLayersName) {
         const urlLayersName = urlMethodsLayersName[method];
         if ('GET' === method) {
-          for (const url in urlLayersName ) {
+          for (const _url in urlLayersName ) {
+            //set base url
+            let url = _url;
```
Comment (Raruto) [inline src/components/CatalogLayersLegendItems.vue]: please try to avoid this double assignment

Comment (volterra79) [reply src/components/CatalogLayersLegendItems.vue]: @Raruto it was a refuse after refactor

File: src/components/CatalogLayersLegendItems.vue [hunk 2]
```diff
@@ -83,14 +83,74 @@ export default {
       legendurl.loading = false;
     },
 
+    /**
+     * @FIXME add parameter types
+     * @FIXME add return type
+     * @FIXME missing return value when `catalogLayer` is not defined
+     * 
+     * @returns {string}
+     */
```
Comment (Raruto) [inline src/components/CatalogLayersLegendItems.vue]: Check these above comments before merge.

As for the rest it seems to me to be fine 👌

**Review by Raruto — APPROVED** [review]
