### PR TITLE
Fix invalid `FORMAT` parameter for external WMS layers

### LINKED ISSUE #530: Wrong GetMap image format used with WMS layers
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When in a project there is a WMS layer, g3w-client use the _GetMap_ request image format coming from the `source` parameter of layer information into '/api/config ' result. Must be used the `wms_getmap_format` parameter value if the layer WMS is not set as external service.

### Steps to reproduce

Try to use the following project:
[epsg-25832_test-wms-eromagna.zip](https://github.com/g3w-suite/g3w-client/files/13728569/epsg-25832_test-wms-eromagna.zip)

### Environment

- g3w-admin: __3.7.dev-20231220141523__
- g3w-client: __3.9.0-beta.1__
- browser: __Firefox 122.0__
- operating system: __Linux 64-bit__

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
In case of external WMS layer, choose the appropriate format in the following order:

1. layer source (`api/config`)
2. `wms_getmap_format` project parameter
3. `image/png`

Closes: #530

### CODE REVIEW

File: src/app/gui/map/mapservice.js [hunk 1]
```diff
@@ -1844,84 +1844,70 @@ proto._setupAllLayers = function() {
...
+      })
+    )
+    .forEach(([id, layers]) => {
+      const layer    = layers[0] || [];
+      const mapLayer = layer.getMapLayer(
+        {
+          id: `layer_${id}`,
+          projection: this.getProjection(),
+          /** @since 3.7.11 */
+          format: (1 === layers.length && layer.isExternalWMS()) ? layer.getSource() && layer.getSource().format : null
```
Comment (Raruto) [inline src/app/gui/map/mapservice.js]: @volterra79 do you think it's possible to consolidate the `layer.isExternalWMS()` check in here? [src/app/core/layers/map/wmslayer.js#L91](https://github.com/g3w-suite/g3w-client/pull/531/files#diff-fc9f6aaf4a8d83ea2d7df3810f609900bd5e7877bc109a07d85af4da82210a66)

Comment (volterra79) [reply src/app/gui/map/mapservice.js]: @Raruto can you check https://github.com/g3w-suite/g3w-client/pull/531/commits/7e3fbf5e211b926eb9cc8af00c0a722677369fc0 commit

**Review by Raruto — APPROVED** [review]
