### PR TITLE
Fix empty query results for external WMS layers

### LINKED ISSUE #535: No query results found when WMS is set as external
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When set a wms project layer as external, if do a query it show not result also when at least on feature return from server 

### Steps to reproduce

Project ro reproduce error: [regione-toscana_piano-paesistico-toscana.zip](https://github.com/g3w-suite/g3w-client/files/13787689/regione-toscana_piano-paesistico-toscana.zip)

1. Load project on admin
2. Set _Aree tutelate per legge - Lettera d) - Le montagne per la parte eccedente 1.200 msl_ as externl wms
Screenshot from 2023-12-28 16-31-14
3. Query layer
Screenshot from 2023-12-28 16-33-32

### Environment

- g3w-admin: 3.7.1
- g3w-client: 3.9.0

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
## Before

293233177-f4170626-b890-45c5-9d6f-2ef77aaf2ae0

## After

image

Closes: #535

### CODE REVIEW

**Review by Raruto — APPROVED** [review]

File: src/components/QueryResultsActionInfoFormats.vue [hunk 1]
```diff
@@ -58,6 +64,8 @@ export default {
 
     async reloadLayerDataWithChangedContentType(contenttype) {
       this.layer.loading = true;
+      // disable select during get data from server
+      $(this.$el).prop("disabled", true);
```
Comment (Raruto) [inline src/components/QueryResultsActionInfoFormats.vue]:
```suggestion
      this.$el.disabled = true;
```

File: src/components/QueryResultsActionInfoFormats.vue [hunk 2]
```diff
@@ -75,6 +83,8 @@ export default {
         console.log(err);
       }
       this.layer.loading = false;
+      // enable select during get data from server
+      $(this.$el).prop("disabled", false);
```
Comment (Raruto) [inline src/components/QueryResultsActionInfoFormats.vue]:
```suggestion
      this.$el.disabled = false;
```

**Review by Raruto — APPROVED** [review]
