### PR TITLE
:bug:  Fix sort column on query relation table when pagination is set

### LINKED ISSUE #720: Error sorting records of a 1:N relation
### Checklist

- [x] I've searched through the existing [issues](../issues) and this bug has never been reported before

### Subject of the issue

ATTENTION: this error occurs on a specific case and not on our demo

### Steps to reproduce

https://gis3w.arpal.liguria.it/it/map/freatimetri-e-medie/qdjango/45/#

1. Query the TOTAL FEATIMETERS layer
2. Access the MONTHLY AVERAGES report
3. Try sorting by the ID field

Image

Attention: the related historical monthly_averages layer is a PostGis view

### Environment

v 3.9.1

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #720 

Screenshot_20250207_145318

### CODE REVIEW

File: src/components/Catalog.vue [hunk 1]
```diff
@@ -318,7 +318,7 @@ export default {
       legend_position:  ApplicationState.project.state.legend_position || 'tab',
       iframe:           ApplicationState.iframe,
       showlegend:       false,
-      backgroundLegend: ApplicationState.gui.layout.app.legend.transparent ? 'transparent' : '#FFFFFF', //@since 3.11.3 set transparent or white background
+      backgroundLegend: ApplicationState.gui.layout.app.legend && ApplicationState.gui.layout.app.legend.transparent ? 'transparent' : '#FFFFFF', //@since 3.11.3 set transparent or white background
```
Comment (Raruto) [inline src/components/Catalog.vue:321]:
```suggestion
      backgroundLegend: ApplicationState.gui.layout.app?.legend?.transparent ? 'transparent' : '#FFFFFF', //@since 3.11.3 set transparent or white background
```

File: src/components/Relation.vue [hunk 2]
```diff
@@ -454,7 +458,7 @@
             bLengthChange:  true,
             dom:            'ltip',
             columnDefs:     [ this.showTools ? { orderable: false, targets: 0, width: '1%' } : { orderable: true, targets: 0 }],
-            order:          [ this.showTools ? 1 : 0, 'asc' ],
+            order:          [ this.showTools ? this.order.column + 1 : this.order.column, this.order.sort],
```
Comment (Raruto) [inline src/components/Relation.vue]:
```suggestion
            order:          [ this.order.column + (this.showTools ? 1 : 0), this.order.sort],
```

File: src/components/Catalog.vue (hunk 1 above)
Comment (volterra79) [reply src/components/Catalog.vue:321]: @Raruto need to backport to 3.11.x. Is it supported ?.  ?

File: src/components/Relation.vue (hunk 2 above)
Comment (volterra79) [reply src/components/Relation.vue]: @Raruto  we take in account change of columns at when sort change, otherwise we set always the first column

Comment (Raruto) [reply src/components/Relation.vue]: Check again, they seem equivalent to me

**Review by leolami — APPROVED** [review]
