### PR TITLE
Fix unhandled error on query response when `QGIS Project setting -> Add geometry to feature response` is set to false

### LINKED ISSUE #172: Error on result if features has no geometry in response
## Subject of the issue
Get an error if features response has no geometry and result content is not open

Screenshot from 2022-09-09 10-20-59

## Steps to reproduce
1. Be sure that your project has uncheck add geometry to feature response

Screenshot from 2022-09-09 10-38-27

2. Active map query control 

Screenshot from 2022-09-09 10-42-08

3. Click on map

### PR DESCRIPTION
**Pull request by volterra79**
Fix error if features (WMS query) response has no geometry:

Screenshot from 2022-09-09 10-38-27

Screenshot from 2022-09-09 10-20-59

## List of changes

Check for feature geometry existence within function `src/app/core/utils/geo::removeZValueToOLFeatureGeometry({feature, geometryType}={})`

Close https://github.com/g3w-suite/g3w-client/issues/172

### CODE REVIEW

File: src/app/core/utils/parsers.js [hunk 1]
```diff
@@ -117,9 +117,11 @@ const utils = {
 
     // Need to remove Z values due a incorrect addition when using
     // ol.format.WMSGetFeatureInfo readFeatures method from XML
-    // (eg. WMS getFeatureInfo); 
+    // (eg. WMS getFeatureInfo);
+    // Need to check also if feature has geometry in case of
+    // QGIS Project setting -> Add geometry to response is not checked
     if (!is3DGeometry(geometryType)){
-      features.forEach(feature => removeZValueToOLFeatureGeometry({ feature, geometryType }));
+      features.forEach(feature => feature.getGeometry() && removeZValueToOLFeatureGeometry({ feature, geometryType }));
```
Comment (Raruto) [inline src/app/core/utils/parsers.js]: This sanity check should be done within function you are calling, for example after this line?

https://github.com/g3w-suite/g3w-client/blob/b072d237d98b6f0cee9dd509663b863f14799d88/src/app/core/utils/geo.js#L22

**Review by Raruto — APPROVED** [review]
