### PR TITLE
Fix undefined property `queryResponse.query.external` after setting a new query response (ref: editing plugin)

### LINKED ISSUE #368: Case query property is set but its external property is undefined
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

For exmple. In [`layersfids`](https://github.com/g3w-suite/g3w-client/blob/f57c746c1b01dd429f6a800f2fab4ea25a6a812b/src/services/data-search.js#L100) function of `data-search.js` service return a query property that hasn't extenal property.

https://github.com/g3w-suite/g3w-client/blob/f57c746c1b01dd429f6a800f2fab4ea25a6a812b/src/services/data-search.js#L104-L106

In this case

https://github.com/g3w-suite/g3w-client/blob/f57c746c1b01dd429f6a800f2fab4ea25a6a812b/src/app/gui/queryresults/queryresultsservice.js#L1276-L1278

check add value of undefined. It crash

### Steps to reproduce

Run `'search:layersfids'` of `DataRouterService`

### Environment

- g3w-admin: 3.5-dev
- g3w-client: 3.8.0-alpha.1
- browser: all

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #368

### CODE REVIEW

File: src/app/gui/queryresults/queryresultsservice.js [hunk 1]
```diff
@@ -1264,37 +1277,29 @@ proto.getVectorLayerFeaturesFromQueryRequest = function(vectorLayer, query={}) {
 
 };
 
-proto._addVectorLayersDataToQueryResponse = function() {
-  this.onbefore('setQueryResponse', (queryResponse, options = {}) => {
```
Comment (Raruto) [inline src/app/gui/queryresults/queryresultsservice.js:1268]: @volterra79 I've slightly rewrote your bugfix in order to remove the need for the above event listener. Let me know if i did something wrong.

File: src/app/gui/queryresults/queryresultsservice.js [hunk 2]
```diff
@@ -94,23 +94,37 @@ function QueryResultsService() {
...
-    setQueryResponse(queryResponse, options={add:false}) {
-      const {add} = options;
-      // in case of new request results reset the query otherwise maintain the previous request
-      if (!add) {
+    setQueryResponse(queryResponse, options = { add: false }) {
+
+      // set mandatory queryResponse fields
+      if (!queryResponse.data)  queryResponse.data    = [];
+      if (!queryResponse.query) queryResponse.query   = { external: { add: false, filter: {SELECTED: false }}};
+      if (!queryResponse.query.external) queryResponse.query.external = { add: false, filter: {SELECTED: false }};
```
Comment (Raruto) [inline src/app/gui/queryresults/queryresultsservice.js:111]: In the future we might consider rewriting it to something like the following:

```js
// set mandatory queryResponse fields
queryResponse = utils.merge({
  data: [],
  query: {
    external: {
      add: false,
      filter: { SELECTED: false }
    }
  }
}, queryResponse);
```

but that's okay for now 👍

**Review by Raruto — APPROVED** [review]
