### PR TITLE
Fire `changeinput` event also on initial default value of input fields

### LINKED ISSUE #199: `changeinput` event not fired when a new feature field is set with a default value
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

No trigger change event is trigger when new editing feature is created and one ore more field value is set with a default field config value.

### Steps to reproduce

1.  Create a new editing feature (editing config layer has a field with default value) and another field has an expression with this field
2.  No expression api is called

### Environment

All browsers

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
When create new editing feature and layer editing configuration layer has a default value to set when feature is created, can happen that if value of new feature is set with default value, not trigger change is fired. This missing trigger event can create a bug if another field of the feature is related whit an qgis field expression linked with the field.
This fix trigger change event input when a new feature is created and one or mode field have a default value

Closes #199

### CODE REVIEW

File: src/mixins/base-input.js [hunk 1]
```diff
@@ -24,12 +24,15 @@ export default {
     },
     // called when input value change
     change() {
-      this.service.setEmpty();
+      this.service.setEmpty && this.service.setEmpty();
```
Comment (Raruto) [inline src/mixins/base-input.js]: @volterra79 this sounds weird, what are you trying to achieve exactly?

Comment (volterra79) [reply src/mixins/base-input.js]: @Raruto update

File: src/app/gui/inputs/service.js [hunk 2]
```diff
@@ -4,6 +4,8 @@ const {t} = require('core/i18n/i18n.service');
 function Service(options = {}) {
   // set state of input
   this.state = options.state || {};
+  // in case is set default input value to input
+  this.set_input_default_value = false;
```
Comment (Raruto) [inline src/app/gui/inputs/service.js]: @volterra79 is this a setter? maybe not, `has_default_value` or `has_default` would be more self-explanatory?

Comment (volterra79) [reply src/app/gui/inputs/service.js]: @Raruto rename with has_default_value 7011a4a9b63a20eddd6cccd850742f490e213fad

**Review by Raruto — APPROVED** [review]
