### PR TITLE
Fix disabled `"Add WMS Layers Panel"` after changing projection of current selected layer

### LINKED ISSUE #211: Unable to add a custom WMS layer after changing its projection (sidebar panel)
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

When we set a projection on current selected WMS layer, the Add WMS Layer panel rest disabled 

### Steps to reproduce

1. Add wms url on wms sidebar item

Screenshot from 2022-09-27 11-46-38

2. Select a Layer (1) and change Projection (2)

Screenshot from 2022-09-27 11-48-29

3. Add WMS Layer Panel is disabled

Screenshot from 2022-09-27 11-43-24

### Environment

Bug found in version 3.4.0

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #211

Fix misspelling **loading** attribute of a WMSLayersPanel.vue component.
Fix issue of no layers in select layer when all selected layers are removed

Screenshot from 2022-09-27 12-06-12

Screenshot from 2022-09-27 12-04-48

### CODE REVIEW

File: src/components/WMSLayersPanel.vue [hunk 1]
```diff
@@ -71,25 +71,21 @@ export default {
...
   watch: {
-    // when chanhe selected layers
+    // when change selected layers
     selectedlayers(layers){
       if (layers.length) {
         const firstLayer = layers[0];
         if (layers.length === 1) {
           this.epsg = this.layerProjections[firstLayer].crss[0];
-          this.projections = this.layerProjections[firstLayer].crss;
+          this.projections = [...this.layerProjections[firstLayer].crss];
```
Comment (Raruto) [inline src/components/WMSLayersPanel.vue]: @volterra79 Can you add comment above this line? (eg. shallow copy required due to ...)

Comment (volterra79) [reply src/components/WMSLayersPanel.vue]: @Raruto i add new commit without shallow copy

**Review by Raruto — APPROVED** [review]
