### PR TITLE
Fix `[Vue warn]` messages while using the development version of Vue (ref: `vendors/vue/vue.js` file)

### LINKED ISSUE #445: Vue warn messages [Vue warn]
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Fix [Vue warn] messages

Screenshot from 2023-07-11 14-17-16

### Steps to reproduce

1. Change gulpfile  https://github.com/g3w-suite/g3w-client/blob/4ffc68db7525c0338d977fed81094a181b4b61b1/gulpfile.js#L112 to vue.js
2. npm run dev
3. Open Application

### Environment

- g3w-admin: v3.6.x
- g3w-client: v3.8.x
- browser: all

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #445

### CODE REVIEW

File: src/components/Form.vue [hunk 1]
```diff
@@ -38,6 +38,10 @@ import HeaderFormComponent from 'components/FormHeader.vue';
 import G3wFormFooter from 'components/FormFooter.vue';
 
 export default {
+
+  /** @since 3.8.6 */
+  name: 'form',
```
Comment (Raruto) [inline src/components/Form.vue]: I get the following while entering editing mode:

```log
[Vue warn]: Do not use built-in or reserved HTML elements as component id: form
```

**Review by Raruto — CHANGES_REQUESTED** [review]

File: src/components/Form.vue (hunk 1 above)
Comment (volterra79) [reply src/components/Form.vue]: @Raruto ok. i'll change with 'g3w-form'

**Review by Raruto — APPROVED** [review]
