### PR TITLE
Handle reset of strictly nested dependencies (search inputs)

### LINKED ISSUE #642: Search with dependencies inputs
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

In case of a search having than 2 strictly dependencies select inputs, changing first input value  reset only first directly input values

### Steps to reproduce

1- Open a search with 3 input strictly dependencies (**Foglio -> Sezione , Particella -> Foglio**) :
 
Screenshot from 2024-06-26 12-33-54

2 - Set a value of Sezione

Screenshot from 2024-06-26 12-34-30

3 - Set a value of Foglio
Screenshot from 2024-06-26 12-35-07

4 - Set a value of Particella 

Screenshot from 2024-06-26 12-35-32

5 - Change a value Sezione

Screenshot from 2024-06-26 12-36-02

Value and select optison value of foglio are changed. Particella is not set to ALL.

### Environment

- g3w-admin: _v3.7.9_
- g3w-client: _v3.9.9_

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes https://github.com/g3w-suite/g3w-client/issues/642

### CODE REVIEW

File: src/components/SearchPanel.vue [hunk 1]
```diff
@@ -259,31 +253,28 @@
...
             ]));
 
             // value is empty → disable dependants inputs
             d.disabled = is_empty(value) ? d.dependance_strict : false;
 
-            //Check in deep dependencies
-            if (this.state.forminputs
-              .filter(i => i.dependance === d.attribute && (has_select(i) || has_autocomplete(i)))
-              .length > 0
-            ) {
```
Comment (Raruto) [inline src/components/SearchPanel.vue]: @volterra79 double check you too, but they should be equivalent.

**Review by Raruto — APPROVED** [review]
tested with:

image

File: src/components/SearchPanel.vue (hunk 1 above)
Comment (volterra79) [reply src/components/SearchPanel.vue]: @Raruto i think the problem of deep dependecies is due only if the select input is manage by select 2 directive. ChangeInput is fired if the user change select input type , but not if it changed dynamically
