### PR TITLE
Keep initial legend item state (expandend/collapsed) as per QGIS project

### LINKED ISSUE #306: TOC legend layer is not sync with QGIS project
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Layer legend  (collapsed or expanded) is not in sync with G3W-SUITE application when legend is set visible on TOC

Screenshot from 2023-01-17 17-24-16

### Steps to reproduce

1. Set Categories on QGIS project layer collapsed (**building**)

Screenshot from 2023-01-17 17-18-58

2. On G3W-SUITE is show expanded

Screenshot from 2023-01-17 17-19-20

### Environment

- g3w-admin: 3.5
- g3w-client: 3.7.3
- browser: all

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #306 

Layer legend on TOC is collapsed/expanded as in Qgis project layer legend at startup:
 
Screenshot from 2023-01-17 17-18-58

Screenshot from 2023-01-17 17-28-56

### CODE REVIEW

File: src/app/core/layers/geolayermixin.js [hunk 1]
```diff
@@ -25,14 +25,14 @@ proto.setup = function(config={}, options={}) {
...
-  // and adding informations of bbox
+  // and adding information of bbox
   _.extend(this.state, {
     geolayer: config.geometrytype !== "NoGeometry",
     legend: {
       url: null,
       loading: false,
       error: false,
-      show: true
+      show: true /**@deprecated since 3.7. Use expanded attribute instead**/
```
Comment (Raruto) [inline src/app/core/layers/geolayermixin.js]:
```suggestion
     /**
      * @deprecated since 3.8. Will be removed in 4.x. Use expanded attribute instead
      */
      show: true
```

File: src/app/core/layers/geolayermixin.js [hunk 2]
```diff
@@ -45,7 +45,8 @@ proto.setup = function(config={}, options={}) {
     maxscale: config.maxscale,
     ows_method: config.ows_method,
     exclude_from_legend: (typeof config.exclude_from_legend == 'boolean') ? config.exclude_from_legend : true,
-    categories: false // has more than one categories legend
+    categories: false, // has more than one categories legend,
+    expanded: config.expanded /** Add expanded property useful for legend layer on TOC**/
```
Comment (Raruto) [inline src/app/core/layers/geolayermixin.js]:
```suggestion
    /**
     *  Expand or collapse legend item in catalog layers (TOC)
     *
     * @since v3.8
     */
    expanded: config.expanded
```

File: src/app/core/layers/layersstore.js [hunk 3]
```diff
@@ -301,13 +301,14 @@ proto.createLayersTree = function(groupName, options={}) {
...
           if (layer.nodes !== null && layer.nodes !== undefined) {
             lightlayer.title = layer.name;
-            lightlayer.expanded = layer.expanded;
             lightlayer.groupId = uniqueId();
             lightlayer.nodes = [];
             lightlayer.checked = layer.checked;
             lightlayer.mutually_exclusive = layer["mutually-exclusive"];
             traverse(layer.nodes, lightlayer.nodes)
           }
+          /** set expanded property - It used for group and layer that has legend to show on TOC **/
```
Comment (Raruto) [inline src/app/core/layers/layersstore.js]:
```suggestion
          /** toggle expanded property for legend item (TOC) **/
```

**Review by Raruto — CHANGES_REQUESTED** [review]

**Comment by Raruto** [comment]
@volterra79 regarding the pull label, is this a `bug` or simply a change in a previous behavior? (ie. a `ux` change - something that was previously unhandled).

**Comment by volterra79** [comment]
@Raruto 

> @volterra79 regarding the pull label, is this a `bug` or simply a change in a previous behavior? (ie. a `ux` change - something that was previously unhandled).

@Raruto it is a bug. G3W-SUITE application need to follow the QGIS project (as much as possible). So if in QGIS project layer legend is collapsed, as to be collapsed int the G3W-SUITE application too.

**Comment by Raruto** [comment]
> G3W-SUITE application need to follow the QGIS project (as much as possible). So if in QGIS project layer legend is collapsed, as to be collapsed int the G3W-SUITE application too.

Definitely, but previously was this behavior already handled the same way as in QGIS? (if not, i think this could be considered a `ux` change)

**Comment by volterra79** [comment]
> > G3W-SUITE application need to follow the QGIS project (as much as possible). So if in QGIS project layer legend is collapsed, as to be collapsed int the G3W-SUITE application too.
> 
> Definitely, but previously was this behavior already handled the same way as in QGIS? (if not, i think this could be considered a `ux` change)

No. It wasn't handled as QGIS Project. Sure it is ux change but at same time it's a bug of the application.

**Review by Raruto — APPROVED** [review]
