### PR TITLE
Fix unselectable dropdown search form field (sidebar panel)

### LINKED ISSUE #239: Sometimes the dropdown fields in the search widget panel remain disabled (sidebar panel)
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

Sometime select input on search panel remain disabled without any reason

 
Screenshot from 2022-10-19 17-19-56

### Steps to reproduce

Create a Search with select input widget

### Environment

Issue found on v3.7.0-alpha.1

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
Closes: #239

### CODE REVIEW

File: src/directives/v-disabled.js [hunk 1]
```diff
@@ -2,5 +2,8 @@
  * ORIGINAL SOURCE: src/app/gui/vue/directives/v-disabled.js@v3.6
  */
 export default (el, binding) => {
-  el.classList.toggle('g3w-disabled', binding.value);
+  const className = 'g3w-disabled';
+  if (binding.value) {
+    if (!el.classList.contains(className)) el.classList.add(className)
+  } else el.classList.remove(className);
```
Comment (Raruto) [inline src/directives/v-disabled.js:8]: I'm quite sure that the solution adopted before was equivalent to the one you propose...  (is this just an oversight?)

**Ref:** [DOMTokenList/toggle#setting_the_force_parameter](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle#setting_the_force_parameter)
