### PR TITLE
Fixes incorrect use of `GET` for WMS queries when admin setting has `CLIENT_OWS_METHOD = 'POST'`

### LINKED ISSUE #616: Queries HTTP method always GET if inirConfig.baseurl is set
### Checklist

- [X] I've searched through the existing [issues](https://github.com/g3w-suite/g3w-client/issues) and this bug has never been reported before

### Subject of the issue

https://github.com/g3w-suite/g3w-client/commit/b7121e63948dba5f26ff188a8901d2aa701035cd

If  initConfig.baseurl is set, all queries use GET http method

### Steps to reproduce

1. Set a base url
2. Set CLIENT_OWS_METHOD = 'POST' on g3w-admin setting.py
3. Click on map to do a query 

### Environment

- g3w-admin: __3.8.dev-20240430053933__
- g3w-client: __3.10.0-alpha.2__

### Link to your project

_No response_

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by volterra79**
## Depends on: https://github.com/g3w-suite/g3w-admin/pull/836

Closes: #616

### CODE REVIEW

File: src/app/core/layers/imagelayer.js [hunk 1]
```diff
@@ -467,6 +467,21 @@ proto.getFormat = function() {
...
+ * forces to `GET` when wms layer is external or query url isn't a qgis server endpoint (ie. doesn't start with `/ows/`).
+ * 
+ * @since 3.10.0
+ */
+proto.getOwsMethod = function() {
+  return this.isExternalWMS() || !/^\/ows/.test((new URL(this.getQueryUrl(), window.initConfig.baseurl)).pathname)
+    ? 'GET'
+    : this.config.ows_method;
+};
+
```
Comment (Raruto) [inline src/app/core/layers/imagelayer.js:484]: I think this function is enough, If you intend to backport.

**Review by Raruto — APPROVED** [review]
